// Bundles skills/*/SKILL.md into a single importable module.
//
// Workers have no filesystem, so the runtime can't read SKILL.md the way the
// old Express server did. The skills are static content, so we inline them at
// build time instead. Run via `npm run build:skills` (wired into predev/
// predeploy so it can't go stale).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const skillsDir = path.join(root, "skills");
const outFile = path.join(root, "src", "skills.generated.js");

function parseFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { meta: {}, body: raw };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { meta, body: match[2].trim() };
}

const names = fs
  .readdirSync(skillsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((n) => fs.existsSync(path.join(skillsDir, n, "SKILL.md")))
  .sort();

if (names.length === 0) {
  console.error("[build-skills] no skills found in", skillsDir);
  process.exit(1);
}

const skills = names.map((name) => {
  const raw = fs.readFileSync(path.join(skillsDir, name, "SKILL.md"), "utf-8");
  const { meta, body } = parseFrontmatter(raw);
  if (!meta.description) console.warn(`[build-skills] ${name}: no description`);
  return { name, description: meta.description || "", body };
});

const out = `// GENERATED by scripts/build-skills.mjs -- do not edit.
// Source: skills/<name>/SKILL.md (${skills.length} skills)

export const SKILLS = ${JSON.stringify(
  Object.fromEntries(skills.map((s) => [s.name, s])),
  null,
  2
)};

export const SKILL_NAMES = ${JSON.stringify(names, null, 2)};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`[build-skills] ${skills.length} skills -> src/skills.generated.js (${kb} KB)`);
